USE sistemabares;

/*Usuarios*/
INSERT INTO usuario_tb VALUES ('0931974380','JOE','SAVERIO','jsaverio','123','1');
INSERT INTO usuario_tb VALUES ('1310539760','ALIX','FERRIN','aferrin','234','2');
INSERT INTO usuario_tb VALUES ('1310539752','ALEX','FERRIN','apferrin','456','2');

/*Platillos*/
INSERT INTO platillo_tb VALUE ('PLT01', 'CEVICHE DE PESCADO', 'PLATO SERVIDO FRIO QUE CONTIENE PESCADO CURTIDO JUNTO CON TOMATE', 'MARISCOS', 17, 'ceviche_pescado.jpg','PLATO FUERTE','Frio');
INSERT INTO platillo_tb VALUE ('PLT02', 'CEVICHE DE CAMARON', 'PLATO SERVIDO FRIO QUE CONTIENE CAMARON JUNTO CON TOMATE', 'MARISCOS', 17, 'ceviche_camaron.jpg','PLATO FUERTE','Frio');
INSERT INTO platillo_tb VALUE ('PLT03', 'CEVICHE DE CONCHA', 'PLATO SERVIDO FRIO QUE CONTIENE CONCHA JUNTO CON TOMATE', 'MARISCOS', 17, 'ceviche_concha.jpg','PLATO FUERTE','Frio');
INSERT INTO platillo_tb VALUE ('PLT04', 'ARROZ CON MENESTRA Y CARNE', 'PLATO SERVIDO CON ARROZ CON FREJOLES Y CARNE ASADA CON PATACONES', 'CARNES', 25, 'arroz_menestra_carne.jpg','PLATO FUERTE','Caliente');
INSERT INTO platillo_tb VALUE ('PLT05', 'PATACONES CON QUESO Y SALPRIETA', 'PLATO SERVIDO CON VERDE FRITO QUESO Y SALPRIETA (MANI MOLIDO)', 'COMIDA MANABA', 23, 'patacones_queso.jpg','APERITIVO','Caliente');

/*Restaurante*/
INSERT INTO restaurante_tb VALUE ('RST01', 'Restaurante Coca Cola', 'CAMPUS ESPOL FIEC', '01222222', 'JORGE DURAN','1310539760');
INSERT INTO restaurante_tb VALUE ('RST02', 'Restaurante Neo', 'CAMPUES ESPOL EDCOM', '01222222', 'DAYANA OCHOA','1310539752');


















